### ISSUE TITLE
apiauto.ru docs

### ISSUE THREAD

**Issue by artshevtsov** [MaratBo/Calls_bot_vld#1]
https://github.com/MaratBo/Calls_bot_vld/blob/329277be8c2b0754b7924610df11d9c759de7c74/main.py#L29

Hi, can you share apiauto.ru docs? I am working on a similar project and missing the documentation.

**Comment by MaratBo** [comment]
Hi! Yep
https://yandex.ru/dev/autoru/doc/reference/dealer-wallet-product-activations-offer-stats.html

**Comment by artshevtsov** [comment]
Thank you!
